services:
  - type: cron
    name: ainewssummarizer
    env: python
    schedule: "@hourly"
    buildCommand: ""
    startCommand: python main.py
  - type: web
    name: ainewssummarizer-api
    env: python
    buildCommand: ""
    startCommand: python api.py